apiVersion: v1

kind: PersistentVolume

metadata:
    name: pv-volume1

spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 100Mi
    hostPath:
        path: /C/Users/rober/Tmp/k8s-volume1