apiVersion: apps/v1

kind: Deployment

metadata:
    name: postgres-deployment
    labels: 
        app: mypostgres
        type: db
spec:
    template:
        metadata:
            name: postgres-pod
            labels: 
                app: mypostgres
                type: db
        spec:
            containers:
            - name: my-postgres-container
              image: postgres
              volumeMounts:
                - mountPath: "/var/lib/postgresql/data/pgdata"
                  name: postgresvolume
              env:
              - name: PGDATA
                value: "/var/lib/postgresql/data/pgdata"
              - name: POSTGRES_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: myapp-secret
                        key: PGPASSWORD
            volumes:
                - name: postgresvolume
                  persistentVolumeClaim:
                    claimName: postgres-pvc
            
    replicas: 1
    selector:
        matchLabels:
            type: db