apiVersion: apps/v1

kind: Deployment

metadata:
    name: myapp-deployment
    labels: 
        app: myapp
        type: frontend

spec:
    template:
        metadata:
            name: myapp-pod
            labels: 
                app: myapp
                type: frontend

        spec:
            containers:
                - name: mydockerfrontend-web
                  image: rpokrzywniak/myreactapp:latest
                
                
    replicas: 4
    selector:
        matchLabels:
            type: frontend